rootcolor=0x{color7.strip}FF
focuscolor=0x{color10.strip}FF
bordercolor=0x{color8.strip}FF
dropcolor=0x{color12.strip}44
splitcolor=0x{color12.strip}FF
urgentcolor=0x{color4.strip}FF
globalcolor=0x{color14.strip}FF
maximizescreencolor=0x{color13.strip}FF
